/// Seed quest library for new user onboarding and community content.
///
/// Contains 105 curated quests covering all 8 categories, 6 intents,
/// and 4 difficulty levels, plus Auburn-specific quests for beta.
abstract final class SeedQuests {
  /// All seed quests as raw maps for Firestore seeding.
  static const List<Map<String, dynamic>> all = [
    // =========================================================================
    // TRAVEL & ADVENTURE (15)
    // =========================================================================
    {'title':'Watch a sunrise from a new spot','description':'Find somewhere you have never been and watch the sun come up.','category':'travel','difficulty':'easy','intent':['explore'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'location':{'type':'anywhere'},'time':{'type':'timeOfDay','value':'Before sunrise'}}},
    {'title':'Visit a town within 100 miles you have never been to','description':'Pick a random town nearby and spend a few hours exploring.','category':'travel','difficulty':'easy','intent':['explore'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'location':{'type':'city'}}},
    {'title':'Hike a trail you have never done','description':'Find a new trail and hike it start to finish.','category':'travel','difficulty':'medium','intent':['explore','challenge'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'location':{'type':'anywhere'}}},
    {'title':'Take a road trip with no planned destination','description':'Get in the car and drive. Let spontaneity guide you.','category':'travel','difficulty':'medium','intent':['explore','fun'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'prompt':{'question':'Where did you end up?'}}},
    {'title':'Camp under the stars','description':'Spend a night outdoors sleeping under the open sky.','category':'travel','difficulty':'medium','intent':['explore'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'time':{'type':'duration','value':'Overnight'}}},
    {'title':'Visit 3 state parks in one month','description':'Explore at least three different state parks within 30 days.','category':'travel','difficulty':'hard','intent':['explore','challenge'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'stages':{'items':[{'id':'s1','title':'Park 1','xp':50},{'id':'s2','title':'Park 2','xp':50},{'id':'s3','title':'Park 3','xp':50}]}}},
    {'title':'Ride a train somewhere','description':'Take a train to a destination and explore when you arrive.','category':'travel','difficulty':'medium','intent':['explore'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'}}},
    {'title':'Visit every continent','description':'The ultimate travel quest. Set foot on all 7 continents.','category':'travel','difficulty':'legendary','intent':['explore','challenge'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'stages':{'items':[{'id':'s1','title':'North America','xp':100},{'id':'s2','title':'Europe','xp':100},{'id':'s3','title':'Asia','xp':100},{'id':'s4','title':'South America','xp':100},{'id':'s5','title':'Africa','xp':100},{'id':'s6','title':'Oceania','xp':100},{'id':'s7','title':'Antarctica','xp':200}]}}},
    {'title':'Explore a neighborhood you have never walked through','description':'Pick a neighborhood in your city and walk every block.','category':'travel','difficulty':'easy','intent':['explore'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'location':{'type':'city'}}},
    {'title':'Watch a sunset from a rooftop','description':'Find a rooftop with a view and watch the sun go down.','category':'travel','difficulty':'easy','intent':['explore','fun'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'time':{'type':'timeOfDay','value':'Sunset'}}},
    {'title':'Take a ferry or boat somewhere','description':'Travel by water to get somewhere new.','category':'travel','difficulty':'medium','intent':['explore'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'}}},
    {'title':'Go somewhere you need a passport','description':'Cross an international border.','category':'travel','difficulty':'hard','intent':['explore'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'}}},
    {'title':'Sleep in an unusual place','description':'A treehouse, yurt, houseboat, or converted bus.','category':'travel','difficulty':'medium','intent':['explore','fun'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'prompt':{'question':'Where did you sleep?'}}},
    {'title':'Navigate somewhere using only a paper map','description':'No GPS. Just you and a map.','category':'travel','difficulty':'hard','intent':['challenge'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'constraint':{'text':'No GPS or phone maps allowed'}}},
    {'title':'Visit a UNESCO World Heritage Site','description':'Experience a place recognized for its outstanding value to humanity.','category':'travel','difficulty':'hard','intent':['explore','growth'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'location':{'type':'specific'}}},
    // =========================================================================
    // FOOD & DRINK (12)
    // =========================================================================
    {'title':'Cook a dish from a culture you know nothing about','description':'Research a cuisine and cook a traditional dish from scratch.','category':'food','difficulty':'medium','intent':['growth'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'beforeAfter'},'prompt':{'question':'What did you learn?'}}},
    {'title':'Try a fruit you have never eaten','description':'Find an exotic fruit at a market and taste it.','category':'food','difficulty':'easy','intent':['fun','explore'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'}}},
    {'title':'Eat at a restaurant where you cannot read the menu','description':'Go somewhere with a language you do not speak and order adventurously.','category':'food','difficulty':'medium','intent':['explore','fun'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'prompt':{'question':'What did you end up ordering?'}}},
    {'title':'Host a dinner party for 6+ people','description':'Plan, cook, and host a full dinner party.','category':'food','difficulty':'hard','intent':['connection','create'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'people':{'type':'group','minCount':6}}},
    {'title':'Bake bread from scratch','description':'No bread machine. Just flour, water, yeast, and your hands.','category':'food','difficulty':'medium','intent':['create'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'beforeAfter'}}},
    {'title':'Visit a farmers market and cook with what you find','description':'Buy ingredients at a farmers market and improvise a meal.','category':'food','difficulty':'easy','intent':['create','explore'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'}}},
    {'title':'Perfect your signature dish','description':'Cook the same dish 5 times, improving each time.','category':'food','difficulty':'hard','intent':['growth'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'repeat':{'type':'repeatable'}}},
    {'title':'Eat something you think you hate','description':'Give a food you have always avoided another honest chance.','category':'food','difficulty':'easy','intent':['challenge'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'prompt':{'question':'Did your opinion change?'}}},
    {'title':'Make pasta from scratch','description':'Flour, eggs, rolling pin. The real deal.','category':'food','difficulty':'medium','intent':['create'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'beforeAfter'}}},
    {'title':'Have a picnic in an unexpected place','description':'Pack food and eat somewhere you normally would not.','category':'food','difficulty':'easy','intent':['fun'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'location':{'type':'anywhere'}}},
    {'title':'Learn latte art','description':'Master at least one latte art pattern.','category':'food','difficulty':'hard','intent':['create','growth'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'}}},
    {'title':'Complete a food challenge at a restaurant','description':'Find a restaurant with an eating challenge and finish it.','category':'food','difficulty':'legendary','intent':['challenge','fun'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'bonus':{'condition':'Finish within time limit','xpBonus':50}}},
    // =========================================================================
    // FITNESS & SPORTS (12)
    // =========================================================================
    {'title':'Run a 5K','description':'Complete a 5K run — race or solo.','category':'fitness','difficulty':'medium','intent':['challenge'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'}}},
    {'title':'Do 100 push-ups in a day','description':'Break it up however you want. Just hit 100 by midnight.','category':'fitness','difficulty':'medium','intent':['challenge'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'time':{'type':'deadline','value':'By midnight'}}},
    {'title':'Try a sport you have never played','description':'Pick up a new sport and play a full game or session.','category':'fitness','difficulty':'easy','intent':['explore','fun'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'}}},
    {'title':'Hold a plank for 3 minutes','description':'Build up to a 3-minute plank hold.','category':'fitness','difficulty':'hard','intent':['challenge'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'}}},
    {'title':'Swim in open water','description':'A lake, river, or ocean. Not a pool.','category':'fitness','difficulty':'medium','intent':['explore','challenge'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'location':{'type':'anywhere'}}},
    {'title':'Complete a workout every day for 30 days','description':'Any workout counts. Consistency is the challenge.','category':'fitness','difficulty':'legendary','intent':['challenge','growth'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'repeat':{'type':'repeatable'}}},
    {'title':'Learn to do a handstand','description':'Practice until you can hold a freestanding handstand for 5 seconds.','category':'fitness','difficulty':'hard','intent':['challenge','growth'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'}}},
    {'title':'Hike 10 miles in one day','description':'A single day hike covering at least 10 miles.','category':'fitness','difficulty':'hard','intent':['challenge'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'}}},
    {'title':'Take a yoga class','description':'Attend a yoga class — in person or online.','category':'fitness','difficulty':'easy','intent':['growth'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'}}},
    {'title':'Play a pickup game with strangers','description':'Join a pickup game of any sport at a park or gym.','category':'fitness','difficulty':'easy','intent':['connection','fun'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'people':{'type':'stranger'}}},
    {'title':'Run a marathon','description':'26.2 miles. The ultimate running quest.','category':'fitness','difficulty':'legendary','intent':['challenge'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'}}},
    {'title':'Learn to jump rope double-unders','description':'Master the double-under jump rope technique.','category':'fitness','difficulty':'medium','intent':['challenge','growth'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'}}},
    // =========================================================================
    // CREATIVE & ARTS (12)
    // =========================================================================
    {'title':'Fill a sketchbook page from life','description':'Sit somewhere and draw what you see.','category':'creative','difficulty':'easy','intent':['create'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'}}},
    {'title':'Write a short story','description':'Write a complete short story of at least 1000 words.','category':'creative','difficulty':'medium','intent':['create'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'prompt':{'question':'What inspired your story?'}}},
    {'title':'Learn a song on an instrument','description':'Pick up an instrument and learn to play a full song.','category':'creative','difficulty':'medium','intent':['create','growth'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'}}},
    {'title':'Make a piece of pottery','description':'Shape clay into something — a bowl, mug, or sculpture.','category':'creative','difficulty':'medium','intent':['create'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'}}},
    {'title':'Create a mural or large-scale artwork','description':'Go big. Paint or draw something at least 3 feet across.','category':'creative','difficulty':'hard','intent':['create'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'beforeAfter'}}},
    {'title':'Write and perform a poem','description':'Write an original poem and recite it to at least one person.','category':'creative','difficulty':'medium','intent':['create','challenge'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'people':{'type':'withFriend'}}},
    {'title':'Make a short film','description':'Plan, shoot, and edit a short film of at least 2 minutes.','category':'creative','difficulty':'hard','intent':['create'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'}}},
    {'title':'Take 50 photos in one hour','description':'Force yourself to see creatively under time pressure.','category':'creative','difficulty':'easy','intent':['create','fun'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'time':{'type':'duration','value':'1 hour'}}},
    {'title':'Design a poster for an imaginary event','description':'Create a full poster design from scratch.','category':'creative','difficulty':'medium','intent':['create'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'}}},
    {'title':'Paint a self-portrait','description':'Any medium. Any style. Just paint yourself.','category':'creative','difficulty':'medium','intent':['create','growth'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'}}},
    {'title':'Build something with your hands','description':'Woodworking, metalworking, sewing — build a physical object.','category':'creative','difficulty':'hard','intent':['create'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'beforeAfter'}}},
    {'title':'Perform at an open mic','description':'Sing, play, do comedy, read poetry — get on stage.','category':'creative','difficulty':'hard','intent':['challenge','create'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'location':{'type':'specific'}}},
    // =========================================================================
    // SOCIAL & COMMUNITY (12)
    // =========================================================================
    {'title':'Have a real conversation with a stranger','description':'Not small talk. A genuine 10+ minute conversation.','category':'social','difficulty':'medium','intent':['connection'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'people':{'type':'stranger'},'prompt':{'question':'What did you talk about?'}}},
    {'title':'Volunteer for a cause you care about','description':'Give your time to help others.','category':'social','difficulty':'easy','intent':['connection','growth'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'}}},
    {'title':'Organize a game night','description':'Get 4+ friends together for board games or card games.','category':'social','difficulty':'easy','intent':['connection','fun'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'people':{'type':'group','minCount':4}}},
    {'title':'Write a handwritten letter to someone','description':'Not a text. Not an email. A real letter.','category':'social','difficulty':'easy','intent':['connection'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'}}},
    {'title':'Teach someone a skill you know','description':'Share your knowledge with someone who wants to learn.','category':'social','difficulty':'easy','intent':['connection','growth'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'people':{'type':'withFriend'}}},
    {'title':'Reconnect with someone you have lost touch with','description':'Reach out to an old friend and catch up in person.','category':'social','difficulty':'medium','intent':['connection'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'prompt':{'question':'How long had it been?'}}},
    {'title':'Give 5 genuine compliments to strangers in one day','description':'Brighten five peoples day with sincere words.','category':'social','difficulty':'easy','intent':['connection','fun'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'}}},
    {'title':'Attend a community event alone','description':'Go to a meetup, festival, or gathering where you know nobody.','category':'social','difficulty':'medium','intent':['connection','challenge'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'people':{'type':'solo'}}},
    {'title':'Start a book club','description':'Organize a book club and host the first meeting.','category':'social','difficulty':'medium','intent':['connection','growth'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'people':{'type':'group','minCount':3}}},
    {'title':'Mentor someone for a month','description':'Commit to mentoring someone weekly for 4 weeks.','category':'social','difficulty':'hard','intent':['connection','growth'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'time':{'type':'duration','value':'1 month'}}},
    {'title':'Do a random act of kindness every day for a week','description':'Seven days, seven kind acts for strangers.','category':'social','difficulty':'medium','intent':['connection'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'repeat':{'type':'repeatable'}}},
    {'title':'Host a potluck with a theme','description':'Pick a theme and have everyone bring a themed dish.','category':'social','difficulty':'medium','intent':['connection','fun'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'people':{'type':'group','minCount':5}}},
    // =========================================================================
    // CAREER & LEARNING (12)
    // =========================================================================
    {'title':'Read a book in a genre you never read','description':'Step outside your reading comfort zone.','category':'career','difficulty':'easy','intent':['growth'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'prompt':{'question':'What surprised you?'}}},
    {'title':'Take an online course and finish it','description':'Complete a full course — not just start one.','category':'career','difficulty':'medium','intent':['growth'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'}}},
    {'title':'Give a presentation or talk','description':'Present to any audience on a topic you care about.','category':'career','difficulty':'hard','intent':['growth','challenge'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'}}},
    {'title':'Learn 50 words in a new language','description':'Pick a language and learn at least 50 common words.','category':'career','difficulty':'medium','intent':['growth'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'}}},
    {'title':'Shadow someone in a career you are curious about','description':'Spend a day observing someone in a field that interests you.','category':'career','difficulty':'medium','intent':['growth','explore'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'prompt':{'question':'Would you want to do this job?'}}},
    {'title':'Write your 5-year vision','description':'Write down where you want to be in 5 years across all areas of life.','category':'career','difficulty':'easy','intent':['growth'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'}}},
    {'title':'Attend a conference or workshop','description':'Invest in your professional development.','category':'career','difficulty':'medium','intent':['growth'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'}}},
    {'title':'Build a personal website','description':'Create a website showcasing your work or portfolio.','category':'career','difficulty':'hard','intent':['create','growth'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'}}},
    {'title':'Negotiate something you normally would not','description':'Ask for a better price, a raise, or better terms.','category':'career','difficulty':'medium','intent':['growth','challenge'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'prompt':{'question':'What was the outcome?'}}},
    {'title':'Complete a 30-day learning challenge','description':'Learn something new every day for 30 days straight.','category':'career','difficulty':'legendary','intent':['growth','challenge'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'repeat':{'type':'repeatable'}}},
    {'title':'Read 12 books in a year','description':'One book per month. Any genre counts.','category':'career','difficulty':'hard','intent':['growth'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'}}},
    {'title':'Teach a class or workshop','description':'Share your expertise by teaching others.','category':'career','difficulty':'hard','intent':['growth','connection'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'people':{'type':'group'}}},
    // =========================================================================
    // THRILL & ADRENALINE (12)
    // =========================================================================
    {'title':'Go skydiving','description':'Jump out of a perfectly good airplane.','category':'thrill','difficulty':'legendary','intent':['challenge'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'}}},
    {'title':'Ride a roller coaster you are afraid of','description':'Face your fear. Ride the one that scares you most.','category':'thrill','difficulty':'medium','intent':['challenge','fun'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'}}},
    {'title':'Do something that terrifies you','description':'Face a personal fear head-on.','category':'thrill','difficulty':'hard','intent':['challenge'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'constraint':{'text':'Must be legal and safe'},'prompt':{'question':'How did it feel after?'}}},
    {'title':'Go rock climbing outdoors','description':'Climb a real rock face, not just an indoor wall.','category':'thrill','difficulty':'hard','intent':['challenge'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'}}},
    {'title':'Bungee jump','description':'Take the leap. Literally.','category':'thrill','difficulty':'legendary','intent':['challenge'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'}}},
    {'title':'Ride a motorcycle','description':'Learn to ride or take a motorcycle for a spin.','category':'thrill','difficulty':'medium','intent':['explore','challenge'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'}}},
    {'title':'Try white water rafting','description':'Navigate rapids on a river.','category':'thrill','difficulty':'hard','intent':['challenge','fun'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'}}},
    {'title':'Go ziplining','description':'Soar through the air on a zipline.','category':'thrill','difficulty':'medium','intent':['fun'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'}}},
    {'title':'Swim with sharks','description':'Cage dive or snorkel with sharks.','category':'thrill','difficulty':'legendary','intent':['challenge','explore'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'}}},
    {'title':'Do a cold plunge','description':'Submerge in ice-cold water for at least 2 minutes.','category':'thrill','difficulty':'medium','intent':['challenge'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'time':{'type':'duration','value':'2 minutes'}}},
    {'title':'Paraglide or hang glide','description':'Fly without an engine.','category':'thrill','difficulty':'legendary','intent':['challenge','explore'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'}}},
    {'title':'Cliff jump into water','description':'Find a safe cliff jumping spot and take the plunge.','category':'thrill','difficulty':'hard','intent':['challenge','fun'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'constraint':{'text':'Verify depth and safety first'}}},
    // =========================================================================
    // RANDOM / WILDCARD (8)
    // =========================================================================
    {'title':'Say yes to everything for a day','description':'For one full day, say yes to every reasonable request.','category':'random','difficulty':'medium','intent':['fun','challenge'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'time':{'type':'duration','value':'1 day'},'prompt':{'question':'What was the wildest thing you said yes to?'}}},
    {'title':'Let a coin flip decide your day','description':'Heads or tails for every decision.','category':'random','difficulty':'easy','intent':['fun'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'wildcard':{'options':['Heads','Tails']}}},
    {'title':'Do something you did as a kid','description':'Revisit a childhood activity with adult eyes.','category':'random','difficulty':'easy','intent':['fun'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'prompt':{'question':'What did you choose and why?'}}},
    {'title':'Spend a full day without your phone','description':'24 hours. No phone. No cheating.','category':'random','difficulty':'hard','intent':['challenge','growth'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'constraint':{'text':'No smartphone for 24 hours'},'time':{'type':'duration','value':'24 hours'}}},
    {'title':'Learn a magic trick and perform it','description':'Master one magic trick and show it to at least 3 people.','category':'random','difficulty':'medium','intent':['fun','create'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'people':{'type':'group','minCount':3}}},
    {'title':'Take a different route everywhere for a week','description':'No routine paths. Find new ways to get everywhere.','category':'random','difficulty':'easy','intent':['explore'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'time':{'type':'duration','value':'1 week'}}},
    {'title':'Go to a movie you know nothing about','description':'Pick a film at random. No trailers, no reviews.','category':'random','difficulty':'easy','intent':['fun'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'prompt':{'question':'What did you think?'}}},
    {'title':'Wear something completely outside your style','description':'Dress in a way you never would normally.','category':'random','difficulty':'easy','intent':['fun','challenge'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'}}},
    // =========================================================================
    // AUBURN-SPECIFIC (10)
    // =========================================================================
    {'title':'Roll Toomer Corner after an Auburn win','description':'Experience the iconic Auburn tradition of rolling the oaks at Toomer Corner.','category':'social','difficulty':'easy','intent':['fun','connection'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'location':{'type':'specific','value':'Toomer Corner, Auburn, AL'}}},
    {'title':'Walk the Tiger Walk before a game','description':'Line up and cheer the team as they walk into the stadium.','category':'social','difficulty':'easy','intent':['connection','fun'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'location':{'type':'specific','value':'Auburn University'}}},
    {'title':'Take a photo in front of Samford Hall','description':'Get your classic Auburn photo with Samford Hall in the background.','category':'travel','difficulty':'easy','intent':['explore'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'location':{'type':'specific','value':'Samford Hall, Auburn, AL'}}},
    {'title':'Hike every trail at Chewacla State Park','description':'Complete all the trails at Chewacla.','category':'fitness','difficulty':'hard','intent':['challenge','explore'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'location':{'type':'specific','value':'Chewacla State Park, Auburn, AL'}}},
    {'title':'Swim at Lake Martin','description':'Spend a day swimming and boating at Lake Martin.','category':'travel','difficulty':'easy','intent':['fun'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'location':{'type':'specific','value':'Lake Martin, AL'}}},
    {'title':'Eat at every restaurant on College Street','description':'Work your way through the restaurants on College Street in Auburn.','category':'food','difficulty':'hard','intent':['explore','fun'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'location':{'type':'specific','value':'College Street, Auburn, AL'}}},
    {'title':'Watch a sunset from the Auburn intramural fields','description':'Find a spot on the intramural fields and watch the sun set over campus.','category':'travel','difficulty':'easy','intent':['explore'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'location':{'type':'specific','value':'Auburn University'}}},
    {'title':'Pet the eagle at the Raptor Center','description':'Visit the Southeastern Raptor Center and meet Auburn golden eagle.','category':'travel','difficulty':'easy','intent':['explore'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'location':{'type':'specific','value':'Southeastern Raptor Center, Auburn, AL'}}},
    {'title':'Study at every coffee shop in Auburn','description':'Do at least one study session at every coffee shop in town.','category':'career','difficulty':'medium','intent':['explore','growth'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'location':{'type':'city','value':'Auburn, AL'}}},
    {'title':'Attend a First Friday event in downtown Auburn','description':'Experience the art, music, and community of First Friday.','category':'social','difficulty':'easy','intent':['connection','fun'],'creatorId':'sidequest_official','blocks':{'proof':{'type':'photo'},'location':{'type':'specific','value':'Downtown Auburn, AL'}}},
  ];
}
